[tool.poetry]
name = "wizdiff"
version = "0.1.2"
description = "wizard101 version diffing automation tool"
authors = ["StarrFox <starrfox6312@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"
requests = "^2.26.0"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
hypothesis = "^6.17.0"
pytest = "^6.2.4"

[tool.poetry.scripts]
wizdiff = "wizdiff.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
